export { default as BackIcon } from '../src/Assets/Icon/back.svg';
export { default as CrossIcon } from '../src/Assets/Icon/cross.svg';
export { default as HomeIcon } from '../src/Assets/Icon/home.svg';
export { default as MenuIcon } from '../src/Assets/Icon/menu.svg';
export { default as HistoryIcon } from '../src/Assets/Icon/history.svg';
export { default as DashboardIcon } from '../src/Assets/Icon/dashboard.svg';
export { default as RightarrowIcon } from '../src/Assets/Icon/rightarrow.svg';
export { default as TruckIcon } from '../src/Assets/Icon/truck.svg';
export { default as DownarrIcon } from '../src/Assets/Icon/downarr.svg';
export { default as LocationIcon } from '../src/Assets/Icon/location.svg';
export { default as LocationEditIcon } from '../src/Assets/Icon/locationedit.svg';
export { default as TotalorderIcon } from '../src/Assets/Icon/totalorder.svg';
export { default as PendingIcon } from '../src/Assets/Icon/pending.svg';
export { default as ApprovedIcon } from '../src/Assets/Icon/approved.svg';
export { default as PrivacyIcon } from '../src/Assets/Icon/privacy.svg';
export { default as HSIcon } from '../src/Assets/Icon/hs.svg';
export { default as LogoutIcon } from '../src/Assets/Icon/logout.svg';
export { default as AccountIcon } from '../src/Assets/Icon/account.svg';
export { default as EditIcon } from '../src/Assets/Icon/edit.svg';
export { default as HistorytabIcon } from '../src/Assets/Icon/historytab.svg';
export { default as WorkIcon } from '../src/Assets/Icon/work.svg';
export { default as ThreedotIcon } from '../src/Assets/Icon/threedot.svg';
export { default as TickIcon } from '../src/Assets/Icon/tick.svg';
export { default as TickboxIcon } from '../src/Assets/Icon/tickbox.svg';
export { default as ViewIcon } from '../src/Assets/Icon/view.svg';
export { default as StatusIcon } from '../src/Assets/Icon/status.svg';
export { default as DeleteIcon } from '../src/Assets/Icon/delete.svg';
export {default as Down} from '../src/Assets/Icon/down.svg';
export {default as ProductsIcon} from '../src/Assets/Icon/product.svg';
export {default as ShopIcon} from '../src/Assets/Icon/shop.svg';
export {default as CheckboxIcon} from '../src/Assets/Icon/checkbox.svg';
export {default as CheckboxactiveIcon} from '../src/Assets/Icon/checkboxactive.svg';
export { default as UploadIcon } from '../src/Assets/Icon/upload.svg';
export { default as ProfileIcon } from '../src/Assets/Icon/profile.svg';
export { default as PlusIcon } from '../src/Assets/Icon/plus.svg';
export { default as DeliveryIcon } from '../src/Assets/Icon/delivery.svg';
export { default as StarIcon } from '../src/Assets/Icon/star.svg';